encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("newpage", views.newpage, name="newpage"),
    path("randompage", views.randompage, name="randompage"),
    path("wiki/<str:articletitle>", views.article, name='articlepage'),
    path("edit/<str:articletitle>", views.editpage, name='editpage'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse
from markdownify import markdownify as md
import random
import markdown
import os


from . import util

class hiddeninfoform(forms.Form):
    pass

def index(request):
    rendered_entries=[]

    if request.method=="POST":
        query = request.POST.get('q')
        for entry in util.list_entries():
            if entry==query:
                return HttpResponseRedirect("/wiki/"+entry)
            if query in entry:
                rendered_entries+=[entry]
    else:
        rendered_entries = util.list_entries()
    
    return render(request, "encyclopedia/index.html", {
        "entries": rendered_entries
        })

def article(request, articletitle):
    articlecontent = util.get_entry(articletitle)
    if articlecontent==None:
        return HttpResponse("The article " + articletitle + " does not exist!")
    print(articlecontent)
    return render(request, "encyclopedia/article.html", {"titlestr" : articletitle, "articlecontent" : markdown.markdown(articlecontent)}) 

def newpage(request):
    if request.method=="POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        if util.get_entry(title)!=None:
            return HttpResponse("A page with this title already exists!")
        util.save_entry(title,content)
        return HttpResponseRedirect("/wiki/"+title)
    return render(request, "encyclopedia/newpage.html", {
        "action":"/newpage",
        "defaultContent":"",
        "editing":False
    })

def editpage(request, articletitle):
    if request.method=="POST":
        util.save_entry(articletitle,request.POST.get('content'))
        return HttpResponseRedirect("/wiki/"+articletitle)

    return render(request, "encyclopedia/newpage.html",{
        "action":"/edit/"+articletitle,
        "defaultContent":util.get_entry(articletitle),
        "editing":True,
    })

def randompage(request):
    return HttpResponseRedirect("/wiki/"+random.choice(util.list_entries()))

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}
<!---->
{% block title %}
{{ titlestr }}
{% endblock %}
<!---->
{% block body %}
{{ articlecontent | safe }}
{% endblock %}
<!---->
{% block nav %}
<a href="/edit/{{ titlestr }}">Edit page</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
<!---->
{% block title %} Encyclopedia {% endblock %}
<!---->
{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li>
        <a href="wiki/{{ entry }}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
    </head>
    <body style="overflow-x: hidden;">
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index'%}" method="POST">
                    {% csrf_token %}
                    <input
                        class="search"
                        type="text"
                        name="q"
                        id="q"
                        placeholder="Search Encyclopedia"
                    />
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">
                        Create New Page
                    </a>
                </div>
                <div>
                    <a href="/randompage">Random Page</a>
                </div>
                {% block nav %} {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %} {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends 'encyclopedia/layout.html' %}

<!---->
{% block title %} Page editor {% endblock %}
<!---->
{% block body %}
<form action="{{ action }}" method="POST">
    {%csrf_token%}
    <!---->
    {% if not editing %}
    <input
        type="text"
        name="title"
        id="title"
        style="margin: 5vh"
        placeholder="Title"
    />
    {% endif %}
    <br />
    <textarea
        name="content"
        id="content"
        style="min-height:60vh; margin: 5vh; margin-top: 0;"
        class="col-9"
        placeholder="Article content"
        >{{ defaultContent }}</textarea
    >
    <br />
    <input type="submit" style="margin:5vh; margin-top:0;" />
</form>
{% endblock %}